server.port: 9090
security:
  cors:
    allowed-headers: "*" #comma seperated headers
    allowed-methods: "*" #comma seperated methods
    allowed-origins: "http://localhost:8080" #comma seperated url list
  jwt:
    token:
      secret-key: "oeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI-ZQ19k_o9MI0y6eZN2lj9jow55FlXMiINEdv1XR85VipRLSOkT6kSpzs3x-jbLDiz9iFVzkd81YKxMgPA7VfZeQUm4n-mOmnWMaVX30zGFU4L3oPBctYKkl4dYfqYWqRNfrgPJVi5DGFjywgxx0ASEiJHtV72paI3fDR2XwlSkyhhmY-ICjCRmsJN4fX1pdoL8a18-aQrvyu4j0Os6dVPYIoPvvY0SAZtWYKHfM15g7A3HD4cVREf9cUsprCRK93w"
      expire-length: 99600 #in milliseconds